name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17 
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      
      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test with Gradle
        run: gradle test
      - name: Copy Text File
        run: gradle copyResources
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t hotelbookingsystem .
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hotel-booking-system:latest
