name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v2

      # 2. Set execute permission for gradlew
      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      # 3. Set up JDK 17 for the Gradle build
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      # 4. Build the JAR file using Gradle
      - name: Build JAR with Gradle
        run: ./gradlew clean jar

      # 5. Verify the JAR is created
      - name: List build/libs directory
        run: ls -la build/libs

      # 6. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/hotelbookingsystem

      # 8. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
